# Generated by Django 3.1 on 2020-09-01 15:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0002_auto_20200821_2045'),
    ]

    operations = [
        migrations.AlterField(
            model_name='raport',
            name='dateTime',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
